import React from 'react';
import { Terminal, ArrowRightLeft, Code, Trash2, Play } from 'lucide-react';

export default function CodeConfigPanel({ data, onChange, schemaKeys }) {
  const config = data.config || { language: 'python', code: '' };
  const inputMapping = data.input_mapping || {};
  const outputMapping = data.output_mapping || {};

  const handleConfigChange = (field, val) => onChange('config', { ...config, [field]: val });
  const handleInputAdd = () => onChange('input_mapping', { ...inputMapping, [`arg_${Object.keys(inputMapping).length + 1}`]: '' });
  const handleInputChange = (oldKey, newKey, newVal) => { const newMapping = { ...inputMapping }; if (oldKey !== newKey) { delete newMapping[oldKey]; newMapping[newKey] = newVal; } else { newMapping[oldKey] = newVal; } onChange('input_mapping', newMapping); };
  const handleInputDelete = (key) => { const newMapping = { ...inputMapping }; delete newMapping[key]; onChange('input_mapping', newMapping); };

  return (
    <div className="space-y-6">
      <div className="space-y-3"><label className="text-xs font-bold text-slate-500 uppercase tracking-wider flex items-center gap-1"><Terminal size={12} /> 环境配置</label><select value={config.language} onChange={(e) => handleConfigChange('language', e.target.value)} className="w-full bg-white border border-slate-200 rounded px-2 py-1.5 text-xs outline-none focus:border-blue-500"><option value="python">Python 3.10</option><option value="javascript">JavaScript (Node.js)</option></select></div>
      <div className="space-y-3"><div className="flex items-center justify-between"><label className="text-xs font-bold text-slate-500 uppercase tracking-wider flex items-center gap-1"><ArrowRightLeft size={12} /> 入参映射</label><button onClick={handleInputAdd} className="text-[10px] text-blue-600 hover:bg-blue-50 px-2 py-0.5 rounded transition-colors">+ 添加参数</button></div><div className="space-y-2">{Object.entries(inputMapping).map(([argName, schemaKey], idx) => (<div key={idx} className="group relative bg-white border border-slate-200 p-2 rounded-lg flex items-center gap-2 hover:border-blue-300"><div className="flex-1"><span className="text-[9px] text-slate-400 block mb-0.5">代码变量</span><input type="text" value={argName} onChange={(e) => handleInputChange(argName, e.target.value, schemaKey)} className="w-full text-xs font-mono text-blue-600 outline-none border-b border-transparent focus:border-blue-200" /></div><div className="text-slate-300">←</div><div className="flex-1"><span className="text-[9px] text-slate-400 block mb-0.5">Schema</span><select value={schemaKey} onChange={(e) => handleInputChange(argName, argName, e.target.value)} className="w-full text-xs text-slate-700 outline-none bg-transparent"><option value="" disabled>选择...</option>{schemaKeys.map(k => <option key={k} value={k}>{k}</option>)}</select></div><button onClick={() => handleInputDelete(argName)} className="absolute -top-2 -right-2 bg-white border rounded-full p-0.5 text-slate-400 hover:text-red-500 opacity-0 group-hover:opacity-100"><Trash2 size={10} /></button></div>))}</div></div>
      <div className="space-y-2"><label className="text-xs font-bold text-slate-500 uppercase tracking-wider flex items-center gap-1"><Code size={12} /> 核心代码</label><div className="relative border border-slate-200 rounded-lg overflow-hidden"><div className="bg-slate-50 px-3 py-1 border-b border-slate-200 flex justify-between items-center"><span className="text-[10px] text-slate-500 font-mono">main.{config.language === 'python' ? 'py' : 'js'}</span><Play size={10} className="text-green-500 cursor-pointer" /></div><textarea className="w-full h-48 px-3 py-2 bg-[#1e1e1e] text-slate-300 text-xs font-mono outline-none resize-none" placeholder={config.language === 'python' ? "def main(params):\n    return params['arg1'] + 1" : "function main(params) {\n  return params.arg1 + 1;\n}"} value={config.code} onChange={(e) => handleConfigChange('code', e.target.value)} spellCheck="false" /></div></div>
      <div className="space-y-3"><label className="text-xs font-bold text-slate-500 uppercase tracking-wider flex items-center gap-1"><ArrowRightLeft size={12} /> 出参映射</label><div className="p-3 bg-white border border-slate-200 rounded-lg shadow-sm border-l-2 border-l-orange-400"><div className="grid grid-cols-1 gap-2"><div><span className="text-[10px] text-slate-400">Target</span><select value={outputMapping.target || ''} onChange={(e) => onChange('output_mapping', { ...outputMapping, target: e.target.value })} className="w-full mt-1 bg-slate-50 border border-slate-200 rounded px-2 py-1.5 text-xs outline-none focus:border-orange-500"><option value="" disabled>选择变量...</option>{schemaKeys.map(k => <option key={k} value={k}>{k}</option>)}</select></div></div></div></div>
    </div>
  );
}
